### ISSUE TITLE
Fix CfgCvsBasePath tag (remove hardcoding)

### ISSUE THREAD

**Issue by sethcooper** [kakwok/levelOneHCALFM#8]
CfgCVSBasePath should be fixed similarly to RunInfoPublish and used in the FM instead of the hardcoded value in the code.

**Comment by kakwok** [comment]
Done in pamSend_v1-0-2. I made a new parameter HCAL_CFGCVSBASEPATH and then pass it alongside with the cfgscript. 
But this is for safety/future developement only, since the LV2s should not be reading those Cfg files anyway. And as of pamSend_v1-0-2, the LV2's not reading anything from CVS.
